-- Northwind Marketing Analytics - Snowflake environment setup
-- Run with a role that can create roles, warehouses, databases, schemas, and grants.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER;

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH_XS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS NORTHWIND;

CREATE SCHEMA IF NOT EXISTS NORTHWIND.RAW;
CREATE SCHEMA IF NOT EXISTS NORTHWIND.SNAPSHOTS;

-- Core dbt privileges
GRANT USAGE ON WAREHOUSE TRANSFORM_WH_XS TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE NORTHWIND TO ROLE TRANSFORMER;

-- dbt creates environment-specific schemas such as
-- PROD_STAGING, PROD_INTERMEDIATE, and PROD_MARTS.
GRANT CREATE SCHEMA ON DATABASE NORTHWIND TO ROLE TRANSFORMER;

-- Read-only access to raw source data
GRANT USAGE ON SCHEMA NORTHWIND.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA NORTHWIND.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NORTHWIND.RAW TO ROLE TRANSFORMER;

-- Snapshot target
GRANT USAGE ON SCHEMA NORTHWIND.SNAPSHOTS TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA NORTHWIND.SNAPSHOTS TO ROLE TRANSFORMER;
