-- Raw source tables expected by the dbt project.
-- Load the synthetic CSV files into these tables after creation.

USE ROLE ACCOUNTADMIN;
USE DATABASE NORTHWIND;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID VARCHAR,
    EMAIL VARCHAR,
    SIGNUP_DATE DATE,
    ACQUISITION_CHANNEL VARCHAR
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ORDER_TIMESTAMP TIMESTAMP_NTZ,
    AMOUNT NUMBER(14,2),
    CURRENCY VARCHAR,
    IS_REFUNDED BOOLEAN
);

CREATE TABLE IF NOT EXISTS WEB_EVENTS (
    EVENT_ID VARCHAR,
    SESSION_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    EVENT_TIMESTAMP TIMESTAMP_NTZ,
    CHANNEL VARCHAR,
    EVENT_TYPE VARCHAR,
    IS_BOT BOOLEAN
);

CREATE TABLE IF NOT EXISTS GOOGLE_ADS_SPEND (
    DATE DATE,
    PLATFORM VARCHAR,
    CAMPAIGN_ID VARCHAR,
    CAMPAIGN_NAME VARCHAR,
    IMPRESSIONS NUMBER,
    CLICKS NUMBER,
    SPEND NUMBER(14,2)
);

CREATE TABLE IF NOT EXISTS META_ADS_SPEND (
    DATE DATE,
    PLATFORM VARCHAR,
    CAMPAIGN_ID VARCHAR,
    CAMPAIGN_NAME VARCHAR,
    IMPRESSIONS NUMBER,
    CLICKS NUMBER,
    SPEND NUMBER(14,2)
);

-- Refresh grants after creating the raw tables.
GRANT SELECT ON ALL TABLES IN SCHEMA NORTHWIND.RAW TO ROLE TRANSFORMER;
